name: Build Windows Wheel with CUDA 12.9

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build-wheel:
    runs-on: windows-latest
    timeout-minutes: 60  # 构建可能较慢，适当延长时间

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CUDA 12.9
      run: |
        $cudaUrl = "https://developer.download.nvidia.com/compute/cuda/12.9.1/local_installers/cuda_12.9.1_576.57_windows.exe"
        $installerPath = "$env:TEMP\cuda_installer.exe"
        Invoke-WebRequest -Uri $cudaUrl -OutFile $installerPath
        Start-Process $installerPath -ArgumentList '-s' -Wait
        # 设置环境变量
        $cudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.9"
        echo "CUDA_PATH=$cudaPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "PATH=$cudaPath\bin;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel ninja

    - name: Install PyTorch with CUDA 12.9
      run: |
        python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu129

    - name: Install DeepSpeed build dependencies
      run: |
        python -m pip install packaging

    - name: Build DeepSpeed wheel
      run: |
        # 克隆DeepSpeed源码
        # git clone https://github.com/deepspeedai/DeepSpeed.git
        # cd DeepSpeed
        # git checkout v0.17.4  # 指定稳定版本
        
        # 配置CUDA路径
        $env:DS_BUILD_CUDA_EXTRA_CFLAGS = "-I$env:CUDA_PATH\include"
        $env:DS_BUILD_CUDA_EXTRA_LDFLAGS = "-L$env:CUDA_PATH\lib\x64"
        
        # 构建wheel
        python setup.py bdist_wheel
        
        # 移动到工作区
        # mkdir ../dist
        # copy dist\*.whl ..\dist\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deepspeed-wheel
        path: D:/a/DeepSpeed/DeepSpeed/dist
